#ifdef TAPPING_TERM
    #undef TAPPING_TERM
#endif
#define RETRO_TAPPING
#define TAPPING_TOGGLE 3
#define TAP_CODE_DELAY 10
// #define USB_POLLING_INTERVAL_MS 10
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
