SRC += wechselbalg.c
# SRC += custom_shift_keys.c

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
CONSOLE_ENABLE = yes
KEYBOARD_SHARED_EP = no
UNICODE_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
